id: I96E41864
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T13:53:40+00:00'
last_modified: '2022-06-07T15:25:08.474380+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27600
  title: བཀའ་བརྒྱུད་ཀྱི་རྣམ་ཐར་ཆེན་མོ་རིན་པོ་ཆེའི་གཏེར་མཛོད་དགོས་འདོད་འབྱུང་གནས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    ACAA:
      image_group_id: I4457
      title: ''
      total_pages: 532
      order: 1
      base_file: ACAA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
