id: I96E41864
legacy_id: P002889
ocr_import_info:
  bdrc_scan_id: W27600
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T13:50:20'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T07:31:44.878451+00:00'
last_modified: 2022-09-02 15:32:23.649367
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W27600
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW27600
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བཀའ་བརྒྱུད་ཀྱི་རྣམ་ཐར་ཆེན་མོ་རིན་པོ་ཆེའི་གཏེར་མཛོད་དགོས་འདོད་འབྱུང་གནས།
  author: རྡོ་རྗེ་མཛེས་འོད།
statistics:
  ocr_word_mean_confidence_index: 0.9260247079914307
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I4457:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4457
      total_pages: 532
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4457.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9260247079914307
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
