id: P002889
initial_creation_type: ocr
source_metadata:
  id: bdr:W27600
  title: བཀའ་བརྒྱུད་ཀྱི་རྣམ་ཐར་ཆེན་མོ་རིན་པོ་ཆེའི་གཏེར་མཛོད་དགོས་འདོད་འབྱུང་གནས
  author: ''
  volumes:
    e9fd7095a3ed4a1bbee767111071e773:
      image_group_id: I4457
      title: ''
      volume_number: 1
      total_pages: 532
